# 带[ ]括号的，就是多选，不带的就是单选,所有选项的 开对应true，关对应false，自行根据需要调整
boss:
  debugger: false
  sayHi: "您好,我有游戏行业工作经验,还有AIGC大模型、PHP,Java,Python,Golang和运维的相关经验,希望应聘这个岗位,期待可以与您进一步沟通,谢谢！"
  keywords: [ "PHP", "大模型", "Golang", "Java", "高级工程师", "后端", "服务端", "web", "IT", "主管", "技术总监", "技术经理" ]
  industry: [ "不限" ]
  cityCode: [ "厦门" ]
  experience: [ "5-10年" ] # 工作经验："应届毕业生", "1年以下", "1-3年", "3-5年", "5-10年", "10年以上"
  jobType: "不限"
  salary: "25-30K"
  degree: [ "不限" ]
  scale: [ "不限" ]
  stage: [ "不限" ]
  expectedSalary: [ 20, 30 ]
  waitTime: 30
  filterDeadHR: true
  enableAI: true
  sendImgResume: false
  deadStatus: [ "2周内活跃", "本月活跃", "2月内活跃", "半年前活跃", "近半年活跃" ]

job51:
  jobArea: [ "厦门" ]
  keywords: [ "PHP", "大模型", "Golang", "Java", "高级工程师", "后端", "服务端", "web", "IT", "主管", "技术总监", "技术经理" ]
  salary: [ "不限" ]

lagou:
  keywords: [ "PHP", "大模型", "Golang", "Java", "高级工程师", "后端", "服务端", "web", "IT", "主管", "技术总监", "技术经理" ]
  cityCode: "厦门"
  salary: "不限"
  scale: [ "不限" ]
  gj: "在校/应届,3年及以下"

liepin:
  cityCode: "厦门"
  keywords: [ "PHP", "大模型", "Golang", "Java", "高级工程师", "后端", "服务端", "web", "IT", "主管", "技术总监", "技术经理" ]
  salary: "15$30" # 填 15$30 代表 15k-30k
  pubTime: "30"

zhilian:
  cityCode: "厦门"
  salary: "25001,35000"
  keywords: [ "PHP", "大模型", "Golang", "Java", "高级工程师", "后端", "服务端", "web", "IT", "主管", "技术总监", "技术经理" ]

ai:
  introduce: "你是一个专业的求职顾问，擅长根据职位描述(JD)和求职者简历内容，撰写个性化的求职招呼语。"
  prompt: "你是一个专业的求职顾问，擅长根据职位描述(JD)和求职者简历内容，撰写个性化的求职招呼语。请根据以下信息生成一段个性化的招呼语：nn我的个人简介：%snn我期望的职位关键词：%snn职位名称：%snn职位描述(JD)：%snn我预设的招呼语：%snn请根据职位描述和我的个人简介，判断这个职位是否匹配我的背景。如果匹配，请基于职位描述和我的背景，生成一段个性化的招呼语，招呼语需要体现我对这个职位的兴趣和适配度。如果不匹配，请直接回复false。"

bot:
  is_send: false
  is_bark_send: false
